# Generated by Django 4.2.4 on 2023-09-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_suggestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='suggestion',
            new_name='suggestions',
        ),
    ]
